spring:
  application:
    name: pos-restaurant

  datasource:
    url: jdbc:mysql://localhost:3306/pos_db
    username: java
    password: Theburgery1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

server:
  port: 8080
  servlet:
    context-path: /api/v1/theburgery

logging:
  level:
    "[org.springframework]": INFO

security:
  jwt:
    secret-key: 
    token-expiration: 600000
